"""removes roles class

Revision ID: d60da8314889
Revises: fac9f5e02c8b
Create Date: 2021-06-14 16:03:29.099729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd60da8314889'
down_revision = 'fac9f5e02c8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    op.drop_constraint('users_roleId_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'roleId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('roleId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_roleId_fkey', 'users', 'roles', ['roleId'], ['id'])
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='roles_pkey')
    )
    # ### end Alembic commands ###
