"""add user mixing to users

Revision ID: fac9f5e02c8b
Revises: 60471cdbe0db
Create Date: 2021-06-14 09:41:58.529111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fac9f5e02c8b'
down_revision = '60471cdbe0db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pitches_postedBy_fkey', 'pitches', type_='foreignkey')
    op.create_foreign_key(None, 'pitches', 'users', ['postedBy'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.create_foreign_key('pitches_postedBy_fkey', 'pitches', 'profiles', ['postedBy'], ['id'])
    # ### end Alembic commands ###
